- platform: apcupsd
- platform: threshold
  name: dark_sky_cloudy
  entity_id: sensor.dark_sky_cloud_cover
  type: upper
  threshold: 80
- platform: workday
  country: US
  workdays:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
