language: python
cache: pip
python:
  - "3.5"
notifications:
  email:
    - ryan@stickystyle.net
install: "pip install homeassistant==0.40.1"
script:
  - cp .travis/secrets.yaml .
  - hass --script check_config -c .