homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

frontend:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: !secret http_base_url

updater:
  
config:

cloud:
  alexa:
    entity_config:
      media_player.family_room_tv:
        name: 'TV'
      switch.family_room_lights:
        name: 'Family Room Lights'
        display_categories: LIGHT
    filter:
      include_entities:
        - scene.bedtime
        - switch.family_room_lights
        - media_player.family_room_tv
        - light.hue_catherines_room
        - light.hue_tuckers_room
        - light.back_door
        - light.fan_light
        - light.entryway
        - light.front_door
        - light.kitchen
        - light.closet
        - light.headboard
        - light.hallway
        - light.laundry_room
        - light.backyard
        - light.huebedroom

map:
  
discovery:
  ignore:
    - plex_mediaserver
    - ikea_tradfri

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
      - scene
      - camera
      - ipban
      - httplogin
      - zone
    entities:
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.travis_build_status
      - sensor.config_changes_to_be_applied
      - sensor.dark_sky_summary
      - sensor.ryans_iphone_battery_state
      - sensor.christas_iphone_battery_state
      - sensor.ryan_to_home
      - sensor.christa_to_home
      
      - binary_sensor.dark_sky_cloudy
      
      - light.huebedroom
      - light.hallway_light_1
      - light.hallway_light_2
      
      - group.living_room_motion_detection
      - group.all_switches
      - group.all_automations
      - group.all_lights
      - group.climate
      - group.kids
      - group.front_yard
      - group.back_yard
      - group.fli
      - group.salon
      - group.evening_scenes
      - group.bedroom_motion_control
      - group.bedroom_lights
      - group.meds_reminder
      
      - camera.family_room
      
      - sun.sun
      
      - input_boolean.meds_taken
      - input_boolean.meds_reminder
      
      - binary_sensor.ac_thermostat_has_leaf
      - binary_sensor.ac_thermostat_is_locked
      - binary_sensor.ac_thermostat_is_using_emergency_heat
      - binary_sensor.ac_thermostat_online
      - binary_sensor.bedroom_motion
      - binary_sensor.workday_sensor
      
      - switch.bedroom_flux
      - switch.interior_flux
      
      - input_boolean.kids_tracker

      - input_select.tv_media_source
      
      - input_slider.bedroom_motion_timeout
      - input_slider.bedroom_motion_light_on
      - input_slider.bedroom_motion_start_hour
      - input_slider.bedroom_motion_start_min
      - input_slider.bedroom_motion_stop_hour
      - input_slider.bedroom_motion_stop_min
      
      - media_player.family_room
      - media_player.spotify

recorder:
  db_url: !secret recorder_db_url

influxdb:
  host: 192.168.10.200
  port: 8086
  max_retries: 10

logger:
  default: warn
  logs:
    requests.packages.urllib3.connectionpool: critical
    urllib3.exceptions.HeaderParsingError: error
    urllib3.connectionpool: error

logbook:
  exclude:
    entities:
      - sensor.catherines_backpack
      - sensor.tuckers_backpack
      - sensor.catherines_powerband
      - sensor.tuckers_powerband
      - binary_sensor.bedroom_motion
      - binary_sensor.ac_thermostat_fan
      - group.bedroom_lights
      - sensor.dark_sky_summary
      - image_processing.dlib_face_family_room
      - image_processing.opencv_family_room

sun:

zeroconf:

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://homeide.theparrishfamily.net
  
ios:
  push:
    categories:
      - name: Meds Not Taken
        identifier: 'MEDS_NOT_TAKEN'
        actions:
          - identifier: 'MARK_MEDS_TAKEN'
            title: 'Mark meds as taken'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

mqtt:
  broker: 192.168.10.200
  port: 1883
  client_id: home-assistant-1
  discovery: true

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

apcupsd:
  host: 192.168.10.200
  port: 3551
  
alert:
  ups_on_battery:
    name: UPS is on battery power
    entity_id: binary_sensor.ups_online_status
    state: 'off'
    repeat: 3
    notifiers:
      - ios_ryans_iphone

tradfri:
  host: 192.168.10.112
  allow_tradfri_groups: true
  
  
device_tracker:
  - platform: asuswrt
    host: 192.168.10.1
    username: !secret asuswrt_user
    password: !secret asuswrt_passwd
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  
ffmpeg:

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.10.200:8081
    name: family_room

image_processing:
  - platform: opencv
    source:
      - entity_id: camera.family_room
  - platform: dlib_face_detect
    source:
      - entity_id: camera.family_room

#microsoft_face:
#  api_key: 04770e74c3004cae98314d1c93abdfd5
#  azure_region: westcentralus

input_select:
  tv_media_source:
    name: Media Source
    options:
      - Xfinity
      - Plex
      - Netflix
      - Hulu
      - Playstation
      - Chromecast
    initial: Xfinity
    icon: mdi:television

# usps:
#  username: !secret sensor_usps_username
#  password: !secret sensor_usps_password

light:
  - platform: hue
    host: 192.168.10.121
    allow_hue_groups: true

automation: !include automations.yaml
# automation old: !include_dir_merge_list automation
group: !include groups.yaml
#input_boolean: !include input_boolean.yaml
# input_select: !include_dir_merge_list input_select
# light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
