homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

frontend:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: !secret http_base_url

updater:
  
discovery:
  ignore:
    - plex_mediaserver

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
      - scene
      - camera
      - ipban
      - httplogin
      - zone
    entities:
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.travis_build_status
      - sensor.config_changes_to_be_applied
      - sensor.dark_sky_summary
      - sensor.ryans_iphone_battery_state
      - sensor.christas_iphone_battery_state
      - sensor.ryan_to_home
      - sensor.christa_to_home
      
      - binary_sensor.dark_sky_cloudy
      
      - light.huebedroom
      
      - group.living_room_motion_detection
      - group.all_switches
      - group.climate
      - group.kids
      - group.front_yard
      - group.back_yard
      - group.fli
      - group.salon
      - group.evening_scenes
      - group.bedroom_motion_control
      - group.bedroom_lights
      
      - camera.living_room_cam
      
      - sun.sun
      
      - input_boolean.meds_taken
      - input_boolean.meds_reminder
      
      - binary_sensor.ac_thermostat_has_leaf
      - binary_sensor.ac_thermostat_is_locked
      - binary_sensor.ac_thermostat_is_using_emergency_heat
      - binary_sensor.ac_thermostat_online
      
      - switch.bedroom_flux
      - switch.interior_flux
      
      - input_boolean.media_select_directv
      
      - input_select.tv_media_source
      
      - input_slider.bedroom_motion_timeout
      - input_slider.bedroom_motion_light_on
      - input_slider.bedroom_motion_start_hour
      - input_slider.bedroom_motion_start_min
      - input_slider.bedroom_motion_stop_hour
      - input_slider.bedroom_motion_stop_min

recorder:
  db_url: !secret recorder_db_url

influxdb:
  host: 192.168.10.200
  port: 32773

logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical

logbook:
  exclude:
    entities:
      - sensor.catherines_backpack
      - sensor.tuckers_backpack
      - sensor.catherines_powerband
      - sensor.tuckers_powerband
      - binary_sensor.bedroom_motion
      - binary_sensor.ac_thermostat_fan
      - group.bedroom_lights

sun:

zeroconf:
  
ios:
  push:
    categories:
      - name: Meds Not Taken
        identifier: 'MEDS_NOT_TAKEN'
        actions:
          - identifier: 'MARK_MEDS_TAKEN'
            title: 'Mark meds as taken'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

emulated_hue:
  type: alexa
  host_ip: 192.168.10.118
  expose_by_default: false
  exposed_domains:
    - light
    - group
    - media_player

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.10.1/24
    track_new_devices: no
    exclude:
      - 192.168.10.118
      - 192.168.10.122

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

apcupsd:
  host: 192.168.10.200
  port: 3551
  
alert:
  ups_on_battery:
    name: UPS is on battery power
    entity_id: binary_sensor.ups_online_status
    state: 'off'
    repeat: 3
    notifiers:
      - ios_ryans_iphone

tradfri:
  host: 192.168.10.112
  allow_tradfri_groups: False
  api_key: !secret tradfri_api_key

camera:
  - platform: mjpeg
    name: Family Room
    mjpeg_url: http://192.168.10.200:8081

# image_processing:
#   - platform: dlib_face_detect
#     source:
#       - entity_id: camera.family_room


automation: !include_dir_merge_list automation
group: !include_dir_merge_named groups
# input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
