# - platform: tplink
#   host: 192.168.10.111
#   name: Nightstand
# - platform: mqtt
#   name: "Bedroom Switch"
#   command_topic: "bedroom/switch1/set"
#   state_topic: "bedroom/switch1/status"
#   retain: true
#   optimistic: false
- platform: flux
  name: Interior Flux
  lights:
    - light.headboard
    - light.fan_light
    - light.couch
    - light.hallway
- platform: flux
  name: Bedroom Flux
  lights:
    - light.headboard
    - light.fan_light