- platform: command_line
  switches:
    family_room_motion:
      command_on: "curl -s http://192.168.10.200:8080/0/detection/start"
      command_off: "curl -s http://192.168.10.200:8080/0/detection/pause"
      command_state: "curl -s http://192.168.10.200:8080/0/detection/status|awk '{print $5}'"
      value_template: '{{ value == "ACTIVE" }}'
      friendly_name: Family Room Detection