default_view:
  view: yes
  entities:
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_summary
    - group.two_of_us
    - group.climate
    - group.family_room
    - group.exterior_lights
    - group.hallway
    - switch.flux
    - group.family_room_camera
    - media_player.family_room_tv
    - media_player.plex
    - scene.bedtime
