default_view:
  view: yes
  entities:
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_summary
    - device_tracker.ryans_iphone
    - device_tracker.christas_iphone
    - group.climate
    - group.family_room
    - group.exterior_lights
    - light.hallway
    - switch.flux
    - group.family_room_camera
    - media_player.family_room_tv
    - media_player.plex
    - scene.bedtime
    - scene.hallway_nightlight
