default_view:
  view: yes
  entities:
    - group.climate
    - media_player.family_room_tv
    - media_player.plex
    - group.family_room
    - group.front_porch
    - group.hallway
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_summary
    - switch.flux