default_view:
  view: yes
  entities:
    - group.two_of_us
    - group.climate
    - media_player.family_room_tv
    - media_player.plex
    - group.family_room
    - group.front_yard
    - group.hallway
    - group.back_yard
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_summary
    - switch.flux
