- platform: cert_expiry
  host: cruzwms.net
  name: cruzwms.net
- platform: cert_expiry
  host: home.theparrishfamily.net
  name: home.theparrishfamily.net
- platform: cert_expiry
  host: b2b.corelogicllc.com
  name: b2b.corelogicllc.com
- platform: cert_expiry
  host: citrix.freightlogistics.com
  name: citrix.freightlogistics.com
- platform: cert_expiry
  host: signature.freightlogistics.com
  name: signature.freightlogistics.com