- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - precip_probability
    - apparent_temperature
    - apparent_temperature_max
    - apparent_temperature_min
    - cloud_cover
    - summary
- platform: mqtt
  name: 'Bedroom Temperature'
  unit_of_measurement: '°F'
  state_topic: 'bedroom/sensor1'
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
- platform: mqtt
  name: 'Bedroom Humidity'
  unit_of_measurement: '%'
  state_topic: 'bedroom/sensor1'
  value_template: '{{ value_json.humidity }}'
- platform: command_line
  name: Config changes to be applied
  command: "/home/homeassistant/.homeassistant/bin/get_pending_commits_sensor.sh"
- platform: netdata
  resources:
    - memory_free
    - system_load
- platform: template
  sensors:
    hallway_away_mode:
      entity_id: climate.hallway
      value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'on') }}"
- platform: apcupsd
  resources:
    - linev
    - loadpct
    - timeleft
    - bcharge
    - status
# need to have an inbound package before usps is enabled
# sensor:
#   - platform: usps
#     username: !secret sensor_usps_username
#     password: !secret sensor_usps_password
- platform: ups
  username: !secret sensor_ups_username
  password: !secret sensor_ups_password