- alias: All interior lights off when gone
  trigger:
    platform: state
    entity_id: sensor.hallway_away_mode
    from: 'False'
    to: 'True'
  condition:
    condition: state
    entity_id: group.interior_lights
    state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: group.interior_lights
    - service: media_player.turn_off
      data:
        entity_id: media_player.family_room_tv
    - service: notify.ios_ryans_iphone
      data:
        title: "Turning off the lights"
        message: "Nobody was home, so I turned off the lights"