- alias: Enable camera when gone
  trigger:
    platform: state
    entity_id: sensor.hallway_away_mode
    from: 'False'
    to: 'True'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.family_room_motion
    - service: notify.ios_ryans_iphone
      data:
        title: "Enabling Motion Detection"
        message: "Nobody was home, so I turned on the camera"

- alias: Disable camera when home
  trigger:
    platform: state
    entity_id: sensor.hallway_away_mode
    from: 'True'
    to: 'False'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.family_room_motion
