- alias: Hallway in evening
  trigger:
    - platform: time
      after: '20:30:00'
    - platform: sun
      event: sunset
  condition:
    condition: state
    entity_id: sensor.hallway_away_mode
    state: 'False'
  action:
    - service: scene.turn_on
      entity_id: scene.hallway_nightlight

