- alias: Hallway in evening
  trigger:
    - platform: time
      at: '20:30:00'
    - platform: sun
      event: sunset
  condition:
    condition: state
    entity_id: sensor.hallway_away_mode
    state: 'False'
  action:
    - service: scene.turn_on
      entity_id: scene.hallway_nightlight

- alias: Arriving home in the evening
  trigger:
    - platform: state
      entity_id: device_tracker.ryans_iphone
      to: 'home'
    - platform: state
      entity_id: device_tracker.christas_iphone
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 3.5
      - condition: state
        entity_id: sensor.hallway_away_mode
        state: 'True'
  action: 
    - service: service.light_turn_on
      entity_id: light.couch_light
    - service: scene.turn_on
      entity_id: scene.hallway_nightlight