- alias: Front porch on in the evening
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: state
    entity_id: sensor.hallway_away_mode
    state: 'False'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_porch
        brightness: 255

- alias: Front porch off in the morning
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  condition:
    condition: state
    entity_id: sensor.hallway_away_mode
    state: 'False'
  action:
    - service: light.turn_off
      data:
        entity_id: light.front_porch

- alias: Front porch on when cloudy
  trigger:
    platform: state
    entity_id: sensor.dark_sky_cloudy
    state: 'on'
    for:
      minutes: 5
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_porch
        brightness: 255

# Turn the front porch light off durring the day if it clears up
- alias: Front porch off when clear
  trigger:
    platform: state
    entity_id: sensor.dark_sky_cloudy
    state: 'off'
    for:
      minutes: 15
  condition:
      condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 3.5
  action:
    - service: light.turn_off
      data:
        entity_id: light.front_porch