- alias: Show evening scenes
  trigger:
    platform: sun
    event: sunset
  action:
    service: group.set_visibility
    entity_id: group.evening_scenes
    data:
      visible: True
      
- alias: Hide evening scenes
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: group.evening_scenes
    data:
      visible: False

- alias: Hide exterior lights
  trigger:
    platform: sun
    event: sunset
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: True
      
- alias: Show exterior lights
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: True
      
- alias: Hide exterior lights
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: False
      
- alias: Hide Two of Us
  trigger:
    platform: state
    entity_id: group.two_of_us
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.ryans_iphone
        state: 'home'
      - condition: state
        entity_id: device_tracker.christas_iphone
        state: 'home'
  action:
    service: group.set_visibility
    entity_id: group.two_of_us
    data:
      visible: False
      
- alias: Show Two of Us
  trigger:
    platform: state
    entity_id: group.two_of_us
    from: 'home'
  action:
    service: group.set_visibility
    entity_id: group.two_of_us
    data:
      visible: True