- alias: Show evening scenes
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      after: '19:30:00'
  action:
    service: group.set_visibility
    entity_id: group.evening_scenes
    data:
      visible: True
      
- alias: Hide evening scenes
  trigger:
    - platform: sun
      event: sunrise
    - platform: time
      after: '07:30:00'
  action:
    service: group.set_visibility
    entity_id: group.evening_scenes
    data:
      visible: False

- alias: Hide exterior lights
  trigger:
    - platform: sun
      event: sunrise
    - platform: time
      after: '07:30:00'
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: False
      
- alias: Show exterior lights
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      after: '19:30:00'
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: True
      
