- alias: Show evening scenes
  trigger:
    platform: sun
    event: sunset
  action:
    service: group.set_visibility
    entity_id: group.evening_scenes
    data:
      visible: True
      
- alias: Hide evening scenes
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: group.evening_scenes
    data:
      visible: False

- alias: Hide exterior lights
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: False
      
- alias: Show exterior lights
  trigger:
    platform: sun
    event: sunset
  action:
    service: group.set_visibility
    entity_id: group.exterior_lights
    data:
      visible: True
      
