- alias: Hallway in evening
  trigger:
    - platform: time
      after: '20:30:00'
    - platform: sun
      event: sunset
  condition:
    condition: state
    entity_id: sensor.hallway_away_mode
    state: 'False'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway_light_1
        brightness: 4
    - service: light.turn_off
      data:
        entity_id: light.hallway_light_2

