- alias: Lights in the morning
  trigger:
    platform: time
    at: '06:15:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.hallway_away_mode
        state: 'False'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: 45
    - service: light.turn_on
      data:
        entity_id: light.couch
        brightness: 45
    - delay:
        minutes: 15
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: 55
    - service: light.turn_on
      data:
        entity_id: light.couch
        brightness: 55

- alias: A/C fan on in the morning
  trigger:
    platform: time
    at: '05:00:00'
  condition:
    condition: state
    entity_id: sensor.hallway_away_mode
    state: 'False'
  action:
    service: climate.set_fan_mode
    data:
      entity_id: climate.ac
      fan_mode: 'On' 
