- alias: Travis build passed
  trigger:
    - platform: state
      entity_id: sensor.travis_build_status
      to: 'passed'
  action:
    - service: notify.ios_ryans_iphone
      data:
        title: "Travis Build"
        message: "Travis build has passed"
        
- alias: Travis build failed
  trigger:
    - platform: state
      entity_id: sensor.travis_build_status
      to: 'failed'
  action:
    - service: notify.ios_ryans_iphone
      data:
        title: "Travis Build"
        message: "Travis build has failed"

# - alias: Merge pending commits when travis build passes
#   trigger:
#     platform: state
#     entity_id: sensor.travis_build_status
#     to: 'passed'
#   condition:
#     condition: numeric_state
#     platform: numeric_state
#     entity_id: sensor.config_changes_to_be_applied
#     above: 0
#   action:
#