- alias: UPS off battery power
  trigger:
    - platform: state
      entity_id: binary_sensor.ups_online_status
      to: 'on'
  action:
    - service: notify.ios_ryans_iphone
      data:
        title: "UPS off battery power"
        message: "Power has been restored"

- alias: UPS on battery power critical
  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_time_left
      below: 15
  action:
    - service: notify.ios_ryans_iphone
      data:
        title: "UPS battery power critical"
        message: "15min remain of battery power, servers shutting down in 5min"