- alias: UPS on battery power
  trigger:
    - platform: state
      entity_id: sensor.status
      to: 'onbatt'
  action:
    - service: notify.pushbullet
      data:
        title: "UPS on battery power"
        message: "The UPS just went to battery power"

- alias: UPS on battery power
  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_time_left
      below: 15
  action:
    - service: notify.pushbullet
      data:
        title: "UPS battery power critical"
        message: "15min remain of battery power, servers shutting down in 5min"