# https://home-assistant.io/docs/ecosystem/ios/notifications/requesting_location_updates/
- alias: Request update from Ryans iPhone
  trigger:
    platform: time
    at: '17:05:00'
  action:
    service: notify.ios_ryans_iphone
    data:
      message: "request_location_update"

- alias: Dad left work
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone
    from: !secret zone_fli_name
  condition:
    condition: and
    conditions:
      - condition: time
        at: '16:55:00'
        before: '17:45:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: notify.ios_ryans_iphone
      data:
        title: "Left work"
        message: "Dad left work, should be home in {{ states.sensor.ryan_to_home.attributes.duration_in_traffic }}"

- alias: Ryan left work
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone
    from: !secret zone_fli_name
  condition:
    condition: and
    conditions:
      - condition: time
        at: '16:55:00'
        before: '17:45:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: notify.ios_christas_iphone
      data:
        title: "Left work"
        message: "Ryan left work, should be home in {{ states.sensor.ryan_to_home.attributes.duration_in_traffic }}"
        

- alias: Christa left work
  trigger:
    platform: state
    entity_id: device_tracker.christas_iphone
    from: !secret zone_salon_name
  condition:
    condition: and
    conditions:
      - condition: time
        at: '18:00:00'
        before: '21:00:00'
        weekday:
          - wed
          - thu
          - fri
          - sat
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: notify.ios_ryans_iphone
      data:
        title: "Left work"
        message: "Christa left work, should be home in {{ states.sensor.christa_to_home.attributes.duration_in_traffic }}"