- platform: plex
- platform: webostv
  name: Family Room TV
  host: 192.168.10.114
  mac: 14:C9:13:36:E6:F6
  customize:
    sources:
      - Comcast
      - Plex
      - Netflix
      - Hulu
      - Playstation