sensor:
  - platform: mqtt_room
    device_id: 0cf3ee00b99e
    name: "Catherine's Backpack"
    state_topic: 'room_presence'
    timeout: 5
    away_timeout: 600
  - platform: mqtt_room
    device_id: 0cf3ee00b974
    name: "Tucker's Backpack"
    state_topic: 'room_presence'
    timeout: 5
    away_timeout: 600
  # - platform: mqtt_room
  #   device_id: f8e8875d2474
  #   name: "Tucker's PowerBand"
  #   state_topic: 'room_presence'
  #   timeout: 5
  #   away_timeout: 600
  # - platform: mqtt_room
  #   device_id: f74ca33698ea
  #   name: "Catherine's PowerBand"
  #   state_topic: 'room_presence'
  #   timeout: 5
  #   away_timeout: 600

input_boolean:
  kids_tracker:
    name: Enable kids tracker
    initial: 'off'

group:
  kids_backpacks:
    name: Kids Backpacks
    entities:
      - sensor.tuckers_backpack
      - sensor.catherines_backpack

# Not going to have an automation to turn away_mode on with these
# as I don't think it would be reliabe enough. Anyways, the kids will
# be with us so our phones will set away_mode
automation:
  - alias: Kids set away mode
    trigger:
      - platform: state
        entity_id: sensor.catherines_backpack
        to: 'family-room'
        from: 'away'
      - platform: state
        entity_id: sensor.tuckers_backpack
        to: 'family-room'
        from: 'away'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.kids_tracker
          state: 'on'
        - condition: template
          value_template: "{{ states.climate.ac.attributes.away_mode == 'on' }}"
        - condition: time
          after: '16:00:00'
          before: '17:45:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
    action:
      service: climate.set_away_mode
      data:
        entity_id: climate.ac
        away_mode: 'off'
        
  - alias: Kids arrived home
    trigger:
      - platform: state
        entity_id: sensor.tuckers_backpack
        to: 'family-room'
        from: 'away'
      - platform: state
        entity_id: sensor.catherines_backpack
        to: 'family-room'
        from: 'away'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.kids_tracker
          state: 'on'
        - condition: time
          after: '16:00:00'
          before: '17:45:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
    action:
      - service: notify.ios_christas_iphone
        data:
          title: "Kids are home"
          message: "The kids have arrived home"
          data:
            push:
              category: camera
            entity_id: camera.family_room
      - service: notify.ios_ryans_iphone
        data:
          title: "Kids are home"
          message: "The kids have arrived home"
          data:
            push:
              category: camera
            entity_id: camera.family_room