input_boolean:
  meds_taken:
    name: Meds have been taken
    initial: False 
    icon: mdi:pill
  meds_reminder:
    name: Meds reminder enabled
    initial: True 

group:
  meds_reminder:
    entities:
      - input_boolean.meds_taken
      - input_boolean.meds_reminder

automation:
  - alias: Reset meds taken
    trigger:
      platform: state
      entity_id: input_boolean.meds_taken
      to: 'on'
      for:
        hours: 2
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.meds_taken
  
  - alias: Mark meds as taken from notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'MARK_MEDS_TAKEN'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.meds_taken

  - alias: Meds have not been taken weekday
    trigger:
      platform: time
      at: '07:15:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: state
          entity_id: input_boolean.meds_reminder
          state: 'on'
        - condition: time
          before: '09:00:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
    action:
      - service: notify.ios_christas_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
          data:
            push:
              category: 'MEDS_NOT_TAKEN'
      - service: notify.ios_ryans_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
          data:
            push:
              category: 'MEDS_NOT_TAKEN'
          
  - alias: Meds have not been taken weekend
    trigger:
      platform: time
      at: '09:45:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: state
          entity_id: input_boolean.meds_reminder
          state: 'on'
        - condition: time
          before: '09:55:00'
          weekday:
            - sat
            - sun
    action:
      - service: notify.ios_christas_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
          data:
            push:
              category: 'MEDS_NOT_TAKEN'
      - service: notify.ios_ryans_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
          data:
            push:
              category: 'MEDS_NOT_TAKEN'
