input_boolean:
  meds_taken:
    name: Meds have been taken
    initial: 'off'

automation:
  - alias: Reset meds taken
    trigger:
      platform: state
      entity_id: input_boolean.meds_taken
      to: 'on'
      for:
        hours: 2
    action:
      service: input_boolean.turn_off

  - alias: Meds have not been taken weekday
    trigger:
      platform: time
      after: '07:24:00'
    condition:
      conditions: and
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: time
          before: '09:00:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
    action:
      - service: notify.ios_christas_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
      - service: notify.ios_ryans_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
          
  - alias: Meds have not been taken weekend
    trigger:
      platform: time
      after: '08:45:00'
      weekday:
        - sat
        - sun
    condition:
      conditions: and
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: time
          before: '09:55:00'
          weekday:
            - sat
            - sun
    action:
      - service: notify.ios_christas_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"
      - service: notify.ios_ryans_iphone
        data:
          title: "Morning Meds"
          message: "Tucker's morning meds have not been taken!"